name: Commnader_Wars_AndroidTest
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.3.0'
  NDK_Version: r22b
  
jobs:
  install:
    name: Android Build
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            COMPILER_VERSION: 'android_armv7'
            qtPath: 'android_armv7'
            target: 'android'
            target-api-level: '27'
            abi : "armeabi-v7a"
            COMPILER_TOOLS_VERSION: 'win64_mingw'
            qtCoreToolsPath: 'mingw_64'
            NdkRoot: 'C:/Android/android-sdk/ndk-bundle'
            ClangPath: "C:/msys64/mingw64/bin"
            
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
             
    - name: Install os qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: 'desktop'
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_TOOLS_VERSION}}
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
            
    - name: setup clang      
      uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-clang        
      
    - name: Configure CMake
      run:  |
        cmake \
        "-B ${{github.workspace}}/build" \
        "-DCMAKE_GENERATOR:STRING=NMake Makefiles JOM" \
        "-DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}" \
        "-DQT_QMAKE_EXECUTABLE:FILEPATH=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/bin/qmake.bat" \
        "-DCMAKE_PREFIX_PATH=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/" \     
        "-DQT_HOST_PATH=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtCoreToolsPath}}" \
        "-DANDROID_NATIVE_API_LEVEL=${{ matrix.target-api-level }}" \
        "-DANDROID_ABI=${{ matrix.abi }}" \
        "-DANDROID_STL:STRING=c++_shared" \
        "-DCMAKE_FIND_ROOT_PATH:PATH=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/" \
        "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{matrix.NdkRoot}}/build/cmake/android.toolchain.cmake" \      
        "-DANDROID_NDK:PATH=${{matrix.NdkRoot}}" \
        "-DQT_NO_GLOBAL_APK_TARGET_PART_OF_ALL:BOOL=ON" \
        "-DCMAKE_C_COMPILER:FILEPATH=${{matrix.ClangPath}}/clang.exe" \
        "-DCMAKE_CXX_COMPILER:FILEPATH=${{matrix.ClangPath}}/clang++.exe" \
        "-DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install"

    - name: Build
      working-directory: '${{github.workspace}}/build'
      run: cmake --build '${{github.workspace}}/build' --config $BUILD_TYPE --target install -j16
