name: Commnader_Wars_AndroidTest
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.3.0'
  NDK_Version: r22b
  
jobs:
  install:
    name: Android Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            COMPILER_VERSION: 'android_armv7'
            qtPath: 'android_armv7'
            qtCoreToolsPath: ''
            target: 'android'
            target-api-level: '27'
            abi : "armeabi-v7a"
        
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v2
          
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: ${{env.NDK_Version}}
        add-to-path: false
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
            
    - name: Install os qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: 'desktop'
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
      
    - name: Configure CMake
      run:  |
        cmake \
        -B "${{github.workspace}}/build" \
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/" \
        -DQt6_DIR="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/lib/cmake/Qt6/" \
        -DQt6CoreTools_DIR="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtCoreToolsPath}}/lib/cmake/Qt6CoreTools/" \
        -DQT_HOST_PATH="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}" \
        -DQT_HOST_PATH_CMAKE_DIR="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/lib/cmake/" \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/lib/cmake/Qt6/qt.toolchain.cmake \
        -DANDROID_NATIVE_API_LEVEL=${{ matrix.target-api-level }} \
        -DANDROID_ABI=${{ matrix.abi }} \
        -DANDROID_NDK_ROOT='${{ steps.setup-ndk.outputs.ndk-path }}' \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install'        

    - name: Build
      working-directory: '${{github.workspace}}/build'
      run: cmake --build '${{github.workspace}}/build' --config $BUILD_TYPE --target install -j16
