name: Commnader_Wars
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.3.1'
  NDK_Version: r22b
  # paths which are given with \ instead of / via windows crashing some command tools
  NDK_Root: 'C:/hostedtoolcache/windows/ndk/r22b/x64'
  workspace: 'D:/a/Commander_Wars/Commander_Wars'
  javaVersion: '17'
  javaDistribution: 'microsoft'
  
jobs:
  install:
    name: All
    strategy:
      fail-fast: false
      matrix:
        buildTarget: [ios-x86_64]
        include:          
          - buildTarget: ios-x86_64
            os: macos-latest
            COMPILER_VERSION: 'clang_64'
            qtPath: 'ios'
            target: 'ios'
            installerCommands1: ''
            installerCommands2: ''
            cmakeOptions: '-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl'
        
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
          path: 'source'
          
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:      
          aqtversion: '==2.0.2'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
        
    - name: Install OS Dependencies 1
      run: ${{matrix.installerCommands1}}
    
    - name: Install OS Dependencies 2
      run: ${{matrix.installerCommands2}}
        
    - name: Configure ios cmake
      if: matrix.target == 'ios-x86_64'
      run:  |
        cmake \
        -S "${{github.workspace}}/source" \
        -B "${{github.workspace}}/build" \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -DCMAKE_INSTALL_PREFIX='${{github.workspace}}/install' \
        -G Xcode
        -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        -DCMAKE_OSX_SYSROOT="iphoneos"
        -DCMAKE_PREFIX_PATH="${{github.workspace}}/qt/Qt/${{env.QT_Version}}/${{matrix.qtPath}}/" \
        -DUPDATESUPPORT=OFF \
        -DCOW_BUILD_TAG="Dummy" \
        -DCOW_UPDATETARGET="Dummy" \
        -DCOW_INSTALLDIR="Commander_Wars_Release" \
        ${{matrix.cmakeOptions}}

    - name: Build other
      working-directory: '${{github.workspace}}/build'
      run: xcodebuild -list -project Commander_Wars.xcodeproj
                    
                    
                    